version: '3.8'

services:
  artist-service:
    build: ./backend/artist-service
    container_name: artist-service
    ports:
      - "5001:5001"
    env_file:
      - ./backend/artist-service/.env
    restart: unless-stopped
